version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/go/src/app
    tty: true
    
  cassandra:
    image: cassandra:latest
    ports:
      - 9044:9042
    environment:
      - CASSANDRA_USER=user
      - CASSANDRA_PASSWORD=pass
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    container_name: cassandra
    restart: always
    volumes:
      - ./pkg/cassandra:/var/lib/cassandra

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./pkg/cassandra/init/schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f ./schema.cql"